FROM ros:humble-desktop-full

# Install dependencies
RUN apt-get update && apt-get install -y \
    ros-humble-nav2* \
    ros-humble-robot-localization \
    ros-humble-turtlebot3_gazebo 

# Install additional packages